import { library, dom } from '@fortawesome/fontawesome-svg-core';

// Import solid weight icons (in alphabetical order)
import {
    faAdjust as fasAdjust,
    faArrowCircleUp as fasArrowCircleUp,
    faBan as fasBan,
    faBarcode as fasBarcode,
    faBatteryHalf as fasBatteryHalf,
    faBell as fasBell,
    faBlog as fasBlog,
    faBolt as fasBolt,
    faBookOpen as fasBookOpen,
    faBroadcastTower as fasBroadcastTower,
    faBuilding as fasBuilding,
    faChartLine as fasChartLine,
    faCheck as fasCheck,
    faCheckCircle as fasCheckCircle,
    faCity as fasCity,
    faClock as fasClock,
    faCloud as fasCloud,
    faCode as fasCode,
    faCog as fasCog,
    faCompass as fasCompass,
    faCompressAlt as fasCompressAlt,
    faCopy as fasCopy,
    faDatabase as fasDatabase,
    faDollarSign as fasDollarSign,
    faDonate as fasDonate,
    faDrawPolygon as fasDrawPolygon,
    faEject as fasEject,
    faEthernet as fasEthernet,
    faExchangeAlt as fasExchangeAlt,
    faExclamationCircle as fasExclamationCircle,
    faExclamationTriangle as fasExclamationTriangle,
    faExpandAlt as fasExpandAlt,
    faExternalLinkAlt as fasExternalLinkAlt,
    faEye as fasEye,
    faFilter as fasFilter,
    faFolder as fasFolder,
    faFolderPlus as fasFolderPlus,
    faHandHoldingHeart as fasHandHoldingHeart,
    faHandPointer as fasHandPointer,
    faHashtag as fasHashtag,
    faHeartbeat as fasHeartbeat,
    faHistory as fasHistory,
    faHome as fasHome,
    faIdCard as fasIdCard,
    faInfo as fasInfo,
    faInfoCircle as fasInfoCircle,
    faLanguage as fasLanguage,
    faLaptop as fasLaptop,
    faLayerGroup as fasLayerGroup,
    faLightbulb as fasLightbulb,
    faLink as fasLink,
    faMagnet as fasMagnet,
    faMapMarkedAlt as fasMapMarkedAlt,
    faMapPin as fasMapPin,
    faMobileAlt as fasMobileAlt,
    faMoon as fasMoon,
    faMousePointer as fasMousePointer,
    faNetworkWired as fasNetworkWired,
    faPeopleArrows as fasPeopleArrows,
    faPlug as fasPlug,
    faQuestionCircle as fasQuestionCircle,
    faRedo as fasRedo,
    faRocket as fasRocket,
    faRoute as fasRoute,
    faSatelliteDish as fasSatelliteDish,
    faSave as fasSave,
    faScroll as fasScroll,
    faSdCard as fasSdCard,
    faSearch as fasSearch,
    faShareAlt as fasShareAlt,
    faShoePrints as fasShoePrints,
    faShoppingCart as fasShoppingCart,
    faSignal as fasSignal,
    faSignInAlt as fasSignInAlt,
    faSignOutAlt as fasSignOutAlt,
    faSitemap as fasSitemap,
    faSkullCrossbones as fasSkullCrossbones,
    faSlidersH as fasSlidersH,
    faSort as fasSort,
    faStar as fasStar,
    faStopwatch as fasStopwatch,
    faSun as fasSun,
    faTable as fasTable,
    faTachometerAlt as fasTachometerAlt,
    faTag as fasTag,
    faTags as fasTags,
    faTerminal as fasTerminal,
    faThermometerHalf as fasThermometerHalf,
    faTimes as fasTimes,
    faTimesCircle as fasTimesCircle,
    faTint as fasTint,
    faTrash as fasTrash,
    faUserCheck as fasUserCheck,
    faUserCog as fasUserCog,
    faUserFriends as fasUserFriends,
    faUserShield as fasUserShield,
    faUserTag as fasUserTag,
    faUserTie as fasUserTie,
    faVirus as fasVirus,
    faWalking as fasWalking,
    faWater as fasWater,
    faWifi as fasWifi
} from '@fortawesome/free-solid-svg-icons';

// Import brand icons (in alphabetical order)
import {
    faAndroid as fabAndroid,
    faApple as fabApple,
    faBluetooth as fabBluetooth,
    faBootstrap as fabBootstrap,
    faCanadianMapleLeaf as fabCanadianMapleLeaf,
    faChrome as fabChrome,
    faCloudflare as fabCloudflare,
    faCreativeCommons as fabCreativeCommons,
    faDiscord as fabDiscord,
    faFacebook as fabFacebook,
    faFontAwesome as fabFontAwesome,
    faGithub as fabGithub,
    faGitSquare as fabGitSquare,
    faInstagram as fabInstagram,
    faJs as fabJs,
    faLinkedin as fabLinkedin,
    faLinux as fabLinux,
    faNodeJs as fabNodeJs,
    faNpm as fabNpm,
    faOsi as fabOsi,
    faRaspberryPi as fabRaspberryPi,
    faSlack as fabSlack,
    faTwitter as fabTwitter,
    faWindows as fabWindows,
    faYoutube as fabYoutube
} from '@fortawesome/free-brands-svg-icons';

// Add icons to library (in alphabetical order)
library.add(
    // Solid
    fasAdjust,
    fasArrowCircleUp,
    fasBan,
    fasBarcode,
    fasBatteryHalf,
    fasBell,
    fasBlog,
    fasBolt,
    fasBookOpen,
    fasBroadcastTower,
    fasBuilding,
    fasChartLine,
    fasCheck,
    fasCheckCircle,
    fasCity,
    fasClock,
    fasCloud,
    fasCode,
    fasCog,
    fasCompass,
    fasCompressAlt,
    fasCopy,
    fasDatabase,
    fasDollarSign,
    fasDonate,
    fasDrawPolygon,
    fasEject,
    fasEthernet,
    fasExchangeAlt,
    fasExclamationCircle,
    fasExclamationTriangle,
    fasExpandAlt,
    fasExternalLinkAlt,
    fasEye,
    fasFilter,
    fasFolder,
    fasFolderPlus,
    fasHandHoldingHeart,
    fasHandPointer,
    fasHashtag,
    fasHeartbeat,
    fasHistory,
    fasHome,
    fasIdCard,
    fasInfo,
    fasInfoCircle,
    fasLanguage,
    fasLaptop,
    fasLayerGroup,
    fasLightbulb,
    fasLink,
    fasMagnet,
    fasMapMarkedAlt,
    fasMapPin,
    fasMobileAlt,
    fasMoon,
    fasMousePointer,
    fasNetworkWired,
    fasPeopleArrows,
    fasPlug,
    fasQuestionCircle,
    fasRedo,
    fasRocket,
    fasRoute,
    fasSatelliteDish,
    fasSave,
    fasScroll,
    fasSdCard,
    fasSearch,
    fasShareAlt,
    fasShoePrints,
    fasShoppingCart,
    fasSignal,
    fasSignInAlt,
    fasSignOutAlt,
    fasSitemap,
    fasSkullCrossbones,
    fasSlidersH,
    fasSort,
    fasStar,
    fasStopwatch,
    fasSun,
    fasTable,
    fasTachometerAlt,
    fasTag,
    fasTags,
    fasTerminal,
    fasThermometerHalf,
    fasTimes,
    fasTimesCircle,
    fasTint,
    fasTrash,
    fasUserCheck,
    fasUserCog,
    fasUserFriends,
    fasUserShield,
    fasUserTag,
    fasUserTie,
    fasVirus,
    fasWalking,
    fasWater,
    fasWifi,

    // Brands
    fabAndroid,
    fabApple,
    fabBluetooth,
    fabBootstrap,
    fabCanadianMapleLeaf,
    fabChrome,
    fabCloudflare,
    fabCreativeCommons,
    fabDiscord,
    fabFacebook,
    fabFontAwesome,
    fabGithub,
    fabGitSquare,
    fabInstagram,
    fabJs,
    fabLinkedin,
    fabLinux,
    fabNodeJs,
    fabNpm,
    fabOsi,
    fabRaspberryPi,
    fabSlack,
    fabTwitter,
    fabWindows,
    fabYoutube
);

// Replace any existing <i> tags with <svg> and set up a MutationObserver to
// continue doing this as the DOM changes.
dom.watch();
