import { library, dom } from '@fortawesome/fontawesome-svg-core';

// Import solid weight icons (in alphabetical order)
import {
    faBarcode as fasBarcode,
    faBatteryHalf as fasBatteryHalf,
    faBlog as fasBlog,
    faBookOpen as fasBookOpen,
    faBroadcastTower as fasBroadcastTower,
    faBuilding as fasBuilding,
    faChartLine as fasChartLine,
    faCheck as fasCheck,
    faCity as fasCity,
    faClock as fasClock,
    faCloud as fasCloud,
    faCode as fasCode,
    faCog as fasCog,
    faCopy as fasCopy,
    faDatabase as fasDatabase,
    faEject as fasEject,
    faEthernet as fasEthernet,
    faExchangeAlt as fasExchangeAlt,
    faExclamationCircle as fasExclamationCircle,
    faExclamationTriangle as fasExclamationTriangle,
    faExternalLinkAlt as fasExternalLinkAlt,
    faEye as fasEye,
    faFilter as fasFilter,
    faFolder as fasFolder,
    faFolderPlus as fasFolderPlus,
    faHandHoldingHeart as fasHandHoldingHeart,
    faHandPointer as fasHandPointer,
    faHashtag as fasHashtag,
    faHeartbeat as fasHeartbeat,
    faHistory as fasHistory,
    faHome as fasHome,
    faInfo as fasInfo,
    faInfoCircle as fasInfoCircle,
    faLanguage as fasLanguage,
    faLaptop as fasLaptop,
    faLayerGroup as fasLayerGroup,
    faLightbulb as fasLightbulb,
    faLink as fasLink,
    faMagnet as fasMagnet,
    faMapMarkedAlt as fasMapMarkedAlt,
    faMapPin as fasMapPin,
    faMousePointer as fasMousePointer,
    faNetworkWired as fasNetworkWired,
    faPeopleArrows as fasPeopleArrows,
    faPlug as fasPlug,
    faQuestionCircle as fasQuestionCircle,
    faRedo as fasRedo,
    faRocket as fasRocket,
    faRoute as fasRoute,
    faScroll as fasScroll,
    faSdCard as fasSdCard,
    faSearch as fasSearch,
    faShoePrints as fasShoePrints,
    faShoppingCart as fasShoppingCart,
    faSignal as fasSignal,
    faSignInAlt as fasSignInAlt,
    faSignOutAlt as fasSignOutAlt,
    faSitemap as fasSitemap,
    faSort as fasSort,
    faStar as fasStar,
    faStopwatch as fasStopwatch,
    faTable as fasTable,
    faTag as fasTag,
    faTags as fasTags,
    faTerminal as fasTerminal,
    faThermometerHalf as fasThermometerHalf,
    faUserFriends as fasUserFriends,
    faUserShield as fasUserShield,
    faUserTag as fasUserTag,
    faWater as fasWater,
    faWifi as fasWifi
} from '@fortawesome/free-solid-svg-icons';

// Import brand icons (in alphabetical order)
import {
    faBluetooth as fabBluetooth,
    faBootstrap as fabBootstrap,
    faCanadianMapleLeaf as fabCanadianMapleLeaf,
    faChrome as fabChrome,
    faCreativeCommons as fabCreativeCommons,
    faFacebook as fabFacebook,
    faFontAwesome as fabFontAwesome,
    faGithub as fabGithub,
    faGitSquare as fabGitSquare,
    faInstagram as fabInstagram,
    faJs as fabJs,
    faLinkedin as fabLinkedin,
    faLinux as fabLinux,
    faNodeJs as fabNodeJs,
    faNpm as fabNpm,
    faOsi as fabOsi,
    faRaspberryPi as fabRaspberryPi,
    faTwitter as fabTwitter
} from '@fortawesome/free-brands-svg-icons';

// Add icons to library (in alphabetical order)
library.add(
    // Solid
    fasBarcode,
    fasBatteryHalf,
    fasBlog,
    fasBookOpen,
    fasBroadcastTower,
    fasBuilding,
    fasChartLine,
    fasCheck,
    fasCity,
    fasClock,
    fasCloud,
    fasCode,
    fasCog,
    fasCopy,
    fasDatabase,
    fasEject,
    fasEthernet,
    fasExchangeAlt,
    fasExclamationCircle,
    fasExclamationTriangle,
    fasExternalLinkAlt,
    fasEye,
    fasFilter,
    fasFolder,
    fasFolderPlus,
    fasHandHoldingHeart,
    fasHandPointer,
    fasHashtag,
    fasHeartbeat,
    fasHistory,
    fasHome,
    fasInfo,
    fasInfoCircle,
    fasLanguage,
    fasLaptop,
    fasLayerGroup,
    fasLightbulb,
    fasLink,
    fasMagnet,
    fasMapMarkedAlt,
    fasMapPin,
    fasMousePointer,
    fasNetworkWired,
    fasPeopleArrows,
    fasPlug,
    fasQuestionCircle,
    fasRedo,
    fasRocket,
    fasRoute,
    fasScroll,
    fasSdCard,
    fasSearch,
    fasShoePrints,
    fasShoppingCart,
    fasSignal,
    fasSignInAlt,
    fasSignOutAlt,
    fasSitemap,
    fasSort,
    fasStar,
    fasStopwatch,
    fasTable,
    fasTag,
    fasTags,
    fasTerminal,
    fasThermometerHalf,
    fasUserFriends,
    fasUserShield,
    fasUserTag,
    fasWater,
    fasWifi,

    // Brands
    fabBluetooth,
    fabBootstrap,
    fabCanadianMapleLeaf,
    fabChrome,
    fabCreativeCommons,
    fabFacebook,
    fabFontAwesome,
    fabGithub,
    fabGitSquare,
    fabInstagram,
    fabJs,
    fabLinkedin,
    fabLinux,
    fabNodeJs,
    fabNpm,
    fabOsi,
    fabRaspberryPi,
    fabTwitter
);

// Replace any existing <i> tags with <svg> and set up a MutationObserver to
// continue doing this as the DOM changes.
dom.watch();